Repository ArkEcosystem/dotnet-client, pull requests merged in 2019-05, with the labels that each got.

#41 doc: update link to Ark documentation
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#44 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#46 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
